defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: storyboard_development

test:
  <<: *defaults
  database: storyboard_test

# set these environment variables on your prod server
production:
  uri: mongodb://heroku_app599079:j9dbudooilos03sde53r50sn96@dbh16.mongolab.com:27167/heroku_app599079

